/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.CodeGenerator.CodeGenerator;
import compiler.Lexer.Lexer;
import compiler.SemanticAnalyzer.SemanticAnalyzer;
import compiler.SemanticAnalyzer.SemanticAnalyzerException;
import compiler.parser.ASTNodes;
import compiler.parser.Parser;
import compiler.parser.ParserException;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;


public class Compiler {
    public static void main(String[] args) throws IOException, SemanticAnalyzerException {

        Path filePath = Path.of(args[0]);

        String input = Files.readString(filePath);
        StringReader reader = new StringReader(input);
        Lexer lexer = new Lexer(reader);
        Parser parser = new Parser(lexer);
        ASTNodes.StatementList sl;
        try {
            sl = parser.parseCode();
        } catch (ParserException e) {
            throw new RuntimeException(e);
        }
        SemanticAnalyzer analyzer = new SemanticAnalyzer(sl);

        analyzer.analyze(sl,analyzer.symbolTable,true);

        CodeGenerator generator = new CodeGenerator(sl);

        generator.generateCode(args[1]);

    }

}
