/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.CodeGenerator.CodeGenerator;
import compiler.Lexer.Lexer;
import compiler.SemanticAnalyzer.SemanticAnalyzer;
import compiler.SemanticAnalyzer.SemanticAnalyzerException;
import compiler.parser.ASTNodes;
import compiler.parser.Parser;
import compiler.parser.ParserException;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;

// javac -classpath asm.jar -sourcepath . Compiler.java CodeGenerator/*.java Lexer/*.java parser/*.java SemanticAnalyzer/*.java Logger/*.java
// en étant dans le dossier "compiler"

// java compiler.Compiler compiler/simple_code_copie.txt MAIN
// en étant dans le dossier "java"

public class Compiler {
    public static void main(String[] args) throws IOException, SemanticAnalyzerException {
        //Path filePath = Path.of("./test/simple_code_copie.txt");
        Path filePath = Path.of(args[0]);

        String input = Files.readString(filePath);
        StringReader reader = new StringReader(input);
        Lexer lexer = new Lexer(reader);
        Parser parser = new Parser(lexer);
        ASTNodes.StatementList sl;
        try {
            sl = parser.parseCode();
        } catch (ParserException e) {
            throw new RuntimeException(e);
        }
        SemanticAnalyzer analyzer = new SemanticAnalyzer(sl);
        System.out.println("111111111111111");
        analyzer.analyze(sl,analyzer.symbolTable,true);
        System.out.println("22222222222222222222");
        CodeGenerator generator = new CodeGenerator(sl);
        System.out.println("bbbbbbbbbbbbbbbbbbbbbbbbbbbbb");
        generator.generateCode(args[1]);

        /*
        System.out.println("------------------------------------------");

        String[] cmd = new String[] {"java", "Main"};
        Process proc = new ProcessBuilder(cmd).start();

        BufferedReader bf =
                new BufferedReader(new InputStreamReader(proc.getInputStream()));

        String line = "";
        while((line = bf.readLine()) != null) {
            System.out.print(line + "\n");
        }

        System.out.println("------------------------------------------");
        */


    }

}
